// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaShop.Persistence.Context;

#nullable disable

namespace PizzaShop.Persistence.Migrations
{
    [DbContext(typeof(PizzaShopDBContext))]
    [Migration("20240519103810_addRole")]
    partial class addRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Традиционная"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Вегетарианская"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Мясная"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Морепродукты"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Гавайская"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Барбекю"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Маргарита"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Пепперони"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ЧетыреСыра"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Суприм"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Мексиканска"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Фермерская"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Кальцоне"
                        },
                        new
                        {
                            Id = 14,
                            Name = "глютенаНет"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Пользовательская"
                        });
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Тесто",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Топпинг",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Соус",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Сып",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Овощи",
                            Price = 0m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Мясо",
                            Price = 0m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Морепродукты",
                            Price = 0m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Травы",
                            Price = 0m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Фрукты",
                            Price = 0m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Орехи",
                            Price = 0m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Молочка",
                            Price = 0m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Зерно",
                            Price = 0m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Приправы",
                            Price = 0m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Масла",
                            Price = 0m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Подсластители",
                            Price = 0m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Другое",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId1")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("SizeId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.PizzaIngredients", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("PizzaId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientId", "PizzaId");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaIngredients");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Маленькая"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Средняя"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Большая"
                        });
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("PizzaShop.Domain.Entities.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaShop.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Pizza", b =>
                {
                    b.HasOne("PizzaShop.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaShop.Domain.Entities.Category", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId1");

                    b.HasOne("PizzaShop.Domain.Entities.Size", "Size")
                        .WithMany("Pizzas")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.PizzaIngredients", b =>
                {
                    b.HasOne("PizzaShop.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaShop.Domain.Entities.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.User", b =>
                {
                    b.HasOne("PizzaShop.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PizzaShop.Domain.Entities.Size", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
